//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College_Fest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class programEntities : DbContext
    {
        public programEntities()
            : base("name=programEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<booking> bookings { get; set; }
        public DbSet<register> registers { get; set; }
        public DbSet<result> results { get; set; }
        public DbSet<tb_event> tb_event { get; set; }
        public DbSet<winner> winners { get; set; }
    }
}
