//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College_Fest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_event
    {
        public tb_event()
        {
            this.bookings = new HashSet<booking>();
            this.results = new HashSet<result>();
            this.winners = new HashSet<winner>();
        }
    
        public int eventid { get; set; }
        public string eventname { get; set; }
        public Nullable<System.DateTime> eventdate { get; set; }
        public string eventimage { get; set; }
        public Nullable<int> entryfee { get; set; }
        public string prize { get; set; }
        public string teamsize { get; set; }
    
        public virtual ICollection<booking> bookings { get; set; }
        public virtual ICollection<result> results { get; set; }
        public virtual ICollection<winner> winners { get; set; }
    }
}
