//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College_Fest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class winner
    {
        public int winid { get; set; }
        public Nullable<int> eid { get; set; }
        public Nullable<int> rid { get; set; }
        public string prizetype { get; set; }
        public string prizewon { get; set; }
    
        public virtual register register { get; set; }
        public virtual tb_event tb_event { get; set; }
    }
}
